server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/task_scheduler
    username: task
    password: task
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    time-zone: UTC
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG